context:
  name: pyrefly
  version: "0.40.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/facebook/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: bf20b3aefbac2df45d305c7b0536070fb0b25b57d2129059ebca0dde0104e72e

build:
  script:
    - if: win
      then:
        # hack: path too long for pixi_config subpackage, https://github.com/prefix-dev/pixi/issues/3691
        - set CARGO_HOME=C:\.cargo
    - cd pyrefly
    - if: unix
      then:
        - export CARGO_PROFILE_RELEASE_STRIP=symbols
        - export CARGO_PROFILE_RELEASE_LTO=fat
        - cargo install --locked --no-track --bins --root ${PREFIX} --path .
      else:
        - set CARGO_PROFILE_RELEASE_STRIP=symbols
        - set CARGO_PROFILE_RELEASE_LTO=fat
        - cargo install --locked --no-track --bins --root %PREFIX% --path .
    - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make

tests:
  - script: pyrefly --help

about:
  homepage: http://pyrefly.org
  summary: A fast type checker and IDE for Python
  description: |
    Pyrefly is a fast type checker for Python. It's designed to replace the existing Pyre type checker at Meta by the end of 2025. This README describes basic usage. See the Pyrefly website for full documentation and a tool for checking code.
  license: MIT
  license_file:
    - LICENSE
    - pyrefly/THIRDPARTY.yml
  documentation: https://pyrefly.org/en/docs/
  repository: https://github.com/facebook/pyrefly

extra:
  recipe-maintainers:
    - pavelzw
