context:
  name: pyrefly
  version: "0.17.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/facebook/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: cc69be968826ee0a20c7c1b92735f408e9f10713e3fbf8954e738b675a5d925b

build:
  script:
    - if: win
      then:
        # hack: path too long for pixi_config subpackage, https://github.com/prefix-dev/pixi/issues/3691
        - set CARGO_HOME=C:\.cargo
    - cd pyrefly
    - if: unix
      then:
        - export CARGO_PROFILE_RELEASE_STRIP=symbols
        - export CARGO_PROFILE_RELEASE_LTO=fat
        - cargo install --locked --no-track --bins --root ${PREFIX} --path .
      else:
        - set CARGO_PROFILE_RELEASE_STRIP=symbols
        - set CARGO_PROFILE_RELEASE_LTO=fat
        - cargo install --locked --no-track --bins --root %PREFIX% --path .
    - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make

tests:
  - script: pyrefly --help

about:
  homepage: http://pyrefly.org
  summary: A fast type checker and IDE for Python
  description: |
    Pyrefly is a fast type checker for Python. It's designed to replace the existing Pyre type checker at Meta by the end of 2025. This README describes basic usage. See the Pyrefly website for full documentation and a tool for checking code.
  license: MIT
  license_file:
    - LICENSE
    - pyrefly/THIRDPARTY.yml
  documentation: https://pyrefly.org/en/docs/
  repository: https://github.com/facebook/pyrefly

extra:
  recipe-maintainers:
    - pavelzw
